### ISSUE TITLE
LDAP to Active Directory Domain Controller

### ISSUE THREAD

**Issue by jcbhltz** [Mailtrain-org/mailtrain#125]
Is LDAP to an Active Directory Domain Controller supported? Domain Controller does not allow anonymous bind. 

I see "Unknown auth type LDAP" on page during login.

**Comment by larrabee** [comment]
Hello. This bug has been fixed by this [PR](https://github.com/Mailtrain-org/mailtrain/pull/178)

**Comment by psy-q** [comment]
This is not fixed, since there is no way to specify a bindDN or bindCredentials option for passport-ldapjs to use. We tried hardcoding those into lib/passport.js but couldn't get that to work either. I'm willing to submit a pull request that reads the required options from production.toml. But how can we debug whether passport-ldapjs is picking up the configured bindDN correctly?

**Comment by witzig** [comment]
Maybe this might shed some light:
- https://github.com/tphuocthai/passport-ldapjs
- https://github.com/tphuocthai/passport-ldapjs/blob/master/lib/strategy.js#L70-L71

**Comment by psy-q** [comment]
This is helpful, thanks. I think when we hardcoded it we already specified things so that they should slot into place as used [there](https://github.com/tphuocthai/passport-ldapjs/blob/master/lib/strategy.js#L70-L71). I will play around with it some more.
