### ISSUE TITLE
V2: sandbox request blocks service behind Traefik reverse proxy

### ISSUE THREAD

**Issue by Kevinjil** [Mailtrain-org/mailtrain#821]
Editing a template in Mailtrain requests a lot of images such as `/c8e91d6542f521c35793be22510000f53474f6f0165ff267/mosaico/templates/2/edres/imageBlock.png`, which keep in a pending state and block the complete application (sandbox, public, and trusted) from responding to any HTTP requests.

I found similar unresolved issues, but not on this repository:
- https://www.reddit.com/r/Traefik/comments/eaegot/traefik_mailtrain_slow_loading_images_from_sandbox/
- https://github.com/containous/traefik/issues/6039

Traefik itself is not blocking or anything similar, as all other services behind the reverse proxy are not impacted in any way.

Mailtrain docker image version: mailtrain/mailtrain:latest (7744f5dc294becf70473c585e543f980287de838)
Traefik image version: v1.7.19-alpine (stable release)

Mailtrain environment:
```
    URL_BASE_TRUSTED: "https://mailtrain.example.com"
    URL_BASE_SANDBOX: "https://sb.mailtrain.example.com"
    URL_BASE_PUBLIC: "https://mailings.example.com"
    WWW_PROXY: "true"
```

I verified that the production config inside the container has set `proxy: true`.

**Comment by luhgit** [comment]
hi @Kevinjil : Did your issue resolve?

**Comment by Kevinjil** [comment]
No, the issue still persists. A single client can cause a DOS of Mailtrain for about a minute.

**Comment by taenzerme** [comment]
I can confirm this is happening with Mailtrain 2 (development branch) and Traefik (2) when opening the Mosaico editor / templates / mailing contents. Not always, but most of the time.

Have not found a solution yet. Any more insights to this?

**Comment by taenzerme** [comment]
This has been fixed by the latest commits in https://github.com/Mailtrain-org/mailtrain/issues/879

**Comment by Kevinjil** [comment]
@taenzerme I updated my deployment and tested in Chrome and Firefox. Problem seems to be resolved. If after more testing I discover the problem is not completely resolved I'll reopen the issue.
